// Stored in JS to make it easier to have static web
// List of lists. First item of internal list is the label for the corresponding lists section
const helms = [
    ["Helmets", "Commoner's Headband", "Commoner's Headband (Altered)", "Aristocrat Headband", "Aristocrat Hat", "Old Aristocrat Cowl",
        "Page Hood",
        "High Page Hood",
        "Guardian Mask",
        "Festive Hood",
        "Festive Hood (Altered)",
        "Blue Festive Hood",
        "Guilty Hood",
        "Prisoner Iron Mask",
        "Blackguard's Iron Mask",
        "Bloodsoaked Mask",
        "Black Dumpling",
        "Mushroom Head",
        "Mushroom Crown"],
    ["", "Astrologer Hood", "Juvenile Scholar Cap", "Karolos Glintstone Crown", "Olivinus Glintstone Crown", 
        "Twinsage Glintstone Crown", "Witch's Glintstone Crown", "Lazuli Glintstone Crown", "Haima Glintstone Crown", 
        "Hierodas Glintstone Crown", "Spellblade's Pointed Hat", "Alberich's Pointed Hat", "Alberich's Pointed Hat (Altered)", 
        "Preceptor's Big Hat", "Mask of Confidence", "Azur's Glintstone Crown", "Lusat's Glintstone Crown", 
        "Queen's Crescent Crown", "Snow Witch Hat", "Fia's Hood", "Prophet Blindfold", "Traveling Maiden Hood", 
        "Finger Maiden Fillet", "Sage Hood", "Greathood", "Radiant Gold Mask"],

    ["", "Perfumer Hood", "Traveler's Hat", "Depraved Perfumer Headscarf", "Ruler's Mask", "Consort's Mask", 
        "Marais Mask", "Great Horned Headband", "Shining Horned Headband", "Godskin Apostle Hood", "Godskin Noble Hood", 
        "Sanguine Noble Hood"],

    ["", "Crimson Tear Scarab", "Cerulean Tear Scarab", "Ash-of-War Scarab", "Glintstone Scarab", "Incantation Scarab", 
        "Imp Head (Cat)", "Imp Head (Wolf)", "Imp Head (Fanged)", "Imp Head (Long-Tongued)", "Imp Head (Corpse)", 
        "Imp Head (Elder)", "Nox Mirrorhelm", "Iji's Mirrorhelm", "Silver Tear Mask", "Envoy Crown", "Octopus Head", 
        "Jar", "Albinauric Mask", "Black Wolf Mask"],

    ["", "Blue Cloth Cowl", "Crimson Hood", "Navy Hood", "White Mask", "Nomadic Merchant's Chapeau", "Bandit Mask", 
        "Black Hood", "Confessor Hood", "Confessor Hood (Altered)", "Omensmirk Mask", "Skeletal Mask"],

    ["", "Foot Soldier Helm", "Foot Soldier Helmet", "Foot Soldier Cap", "Gilded Foot Soldier Cap", "Sacred Crown Helm", 
        "Highwayman Hood", "Vulgar Militia Helm", "Duelist Helm", "Rotten Duelist Helm", "Nox Monk Hood", 
        "Nox Monk Hood (Altered)", "Nox Swordstress Crown", "Nox Swordstress Crown (Altered)", "Night Maiden Twin Crown", 
        "Champion Headband"],

    ["", "Chain Coif", "Iron Helmet", "Godrick Soldier Helm", "Raya Lucarian Helm", "Radahn Soldier Helm", 
        "Leyndell Soldier Helm", "Haligtree Helm", "Exile Hood", "Kaiden Helm", "Land of Reeds Helm", "Okina Mask", 
        "Iron Kasa", "Eccentric's Hood", "Eccentric's Hood (Altered)", "Marionette Soldier Helm", 
        "Marionette Soldier Birdhelm", "Blue Silver Mail Hood", "Fire Monk Hood", "Blackflame Monk Hood", "Zamor Mask", 
        "Black Knife Hood", "Malenia's Winged Helm", "Elden Lord Crown"],

    ["", "Knight Helm", "Vagabond Knight Helm", "Greathelm", "Carian Knight Helm", "Godrick Knight Helm", 
        "Cuckoo Knight Helm", "Redmane Knight Helm", "Gelmir Knight Helm", "Leyndell Knight Helm", "Haligtree Knight Helm", 
        "Bloodhound Knight Helm", "Cleanrot Helm", "Cleanrot Helm (Altered)"],

    ["", "Raging Wolf Helm", "Hoslow's Helm", "Diallos's Mask", "Twinned Helm", "Drake Knight Helm", 
        "Drake Knight Helm (Altered)", "Briar Helm", "Fingerprint Helm", "Royal Remains Helm", "All-Knowing Helm", 
        "Royal Knight Helm", "Maliketh's Helm"],

    ["", "Banished Knight Helm", "Banished Knight Helm (Altered)", "Night's Cavalry Helm", "Night's Cavalry Helm (Altered)", 
        "Veteran's Helm", "Scaled Helm", "Beast Champion Helm", "Tree Sentinel Helm", "Malformed Dragon Helm", 
        "Crucible Axe Helm", "Crucible Tree Helm", "Radahn's Redmane Helm", "Lionel's Helm", "Bull-Goat Helm", 
        "Omen Helm", "Fire Prelate Helm", "Pumpkin Helm"]
]

const chest = [armor_list = [
    "Chest Armor",
    "Cloth Garb",
    "Traveler's Clothes",
    "Commoner's Simple Garb",
    "Commoner's Simple Garb (Altered)",
    "Commoner's Garb",
    "Commoner's Garb (Altered)",
    "Aristocrat Garb",
    "Aristocrat Garb (Altered)",
    "Aristocrat Coat",
    "Old Aristocrat Gown",
    "Page Garb",
    "Page Garb (Altered)",
    "High Page Clothes",
    "High Page Clothes (Altered)",
    "Guardian Garb",
    "Guardian Garb (Full Bloom)",
    "Festive Garb",
    "Festive Garb (Altered)",
    "Blue Festive Garb",
    "Prisoner Clothing",
    "Mushroom Body",
    "Astrologer Robe",
    "Astrologer Robe (Altered)",
    "Juvenile Scholar Robe",
    "Raya Lucarian Robe",
    "Lazuli Robe",
    "Battlemage Robe",
    "Errant Sorcerer Robe",
    "Errant Sorcerer Robe (Altered)",
    "Spellblade's Traveling Attire",
    "Spellblade's Traveling Attire (Altered)",
    "Alberich's Robe",
    "Alberich's Robe (Altered)",
    "Preceptor's Long Gown",
    "Preceptor's Long Gown (Altered)",
    "Azur's Glintstone Robe",
    "Lusat's Robe",
    "Queen's Robe",
    "Snow Witch Robe",
    "Snow Witch Robe (Altered)",
    "Fia's Robe",
    "Fia's Robe (Altered)",
    "Deathbed Dress",
    "Prophet Robe",
    "Prophet Robe (Altered)",
    "Corhyn's Robe",
    "Traveling Maiden Robe",
    "Traveling Maiden Robe (Altered)",
    "Finger Maiden Robe",
    "Finger Maiden Robe (Altered)",
    "Sage Robe",
    "Goldmask's Rags",
    "Perfumer Robe",
    "Perfumer Robe (Altered)",
    "Perfumer's Traveling Garb",
    "Perfumer's Traveling Garb (Altered)",
    "Depraved Perfumer Robe",
    "Depraved Perfumer Robe (Altered)",
    "Upper-Class Robe",
    "Ruler's Robe",
    "Consort's Robe",
    "Official's Attire",
    "Marais Robe",
    "Fur Raiment",
    "Shaman Furs",
    "Godskin Apostle Robe",
    "Godskin Noble Robe",
    "Fell Omen Cloak",
    "Sanguine Noble Robe",
    "Lord of Blood's Robe",
    "Lord of Blood's Robe (Altered)",
    "Leather Armor",
    "Blue Cloth Vest",
    "Noble's Traveling Garb",
    "War Surgeon Gown",
    "War Surgeon Gown (Altered)",
    "Nomadic Merchant's Finery",
    "Nomadic Merchant's Finery (Altered)",
    "Bandit Garb",
    "Confessor Armor",
    "Confessor Armor (Altered)",
    "Omenkiller Robe",
    "Raptor's Black Feathers",
    "Foot Soldier Tabard",
    "Leather-Draped Tabard",
    "Chain-Draped Tabard",
    "Ivory-Draped Tabard",
    "Scarlet Tabard",
    "Bloodsoaked Tabard",
    "Highwayman Cloth Armor",
    "Vulgar Militia Armor",
    "Gravekeeper Cloak",
    "Gravekeeper Cloak (Altered)",
    "Rotten Gravekeeper Cloak",
    "Rotten Gravekeeper Cloak (Altered)",
    "Nox Monk Armor",
    "Nox Monk Armor (Altered)",
    "Nox Swordstress Armor",
    "Nox Swordstress Armor (Altered)",
    "Night Maiden Armor",
    "Champion Pauldron",
    "Chain Armor",
    "Dirty Chainmail",
    "Tree Surcoat",
    "Eye Surcoat",
    "Tree-and-Beast Surcoat",
    "Cuckoo Surcoat",
    "Redmane Surcoat",
    "Erdtree Surcoat",
    "Haligtree Crest Surcoat",
    "Mausoleum Surcoat",
    "Scale Armor",
    "Exile Armor",
    "Kaiden Armor",
    "Land of Reeds Armor",
    "Land of Reeds Armor (Altered)",
    "White Reed Armor",
    "Ronin's Armor",
    "Ronin's Armor (Altered)",
    "Eccentric's Armor",
    "Marionette Soldier Armor",
    "Blue Silver Mail Armor",
    "Blue Silver Mail Armor (Altered)",
    "Fire Monk Armor",
    "Blackflame Monk Armor",
    "Zamor Armor",
    "Black Knife Armor",
    "Black Knife Armor (Altered)",
    "Malenia's Armor",
    "Malenia's Armor (Altered)",
    "Elden Lord Armor",
    "Elden Lord Armor (Altered)",
    "Knight Armor",
    "Vagabond Knight Armor",
    "Vagabond Knight Armor (Altered)",
    "Carian Knight Armor",
    "Carian Knight Armor (Altered)",
    "Godrick Knight Armor",
    "Godrick Knight Armor (Altered)",
    "Cuckoo Knight Armor",
    "Cuckoo Knight Armor (Altered)",
    "Redmane Knight Armor",
    "Redmane Knight Armor (Altered)",
    "Gelmir Knight Armor",
    "Gelmir Knight Armor (Altered)",
    "Leyndell Knight Armor",
    "Leyndell Knight Armor (Altered)",
    "Haligtree Knight Armor",
    "Haligtree Knight Armor (Altered)",
    "Mausoleum Knight Armor",
    "Mausoleum Knight Armor (Altered)",
    "Bloodhound Knight Armor",
    "Bloodhound Knight Armor (Altered)",
    "Cleanrot Armor",
    "Cleanrot Armor (Altered)",
    "Raging Wolf Armor",
    "Raging Wolf Armor (Altered)",
    "Hoslow's Armor",
    "Hoslow's Armor (Altered)",
    "Twinned Armor",
    "Twinned Armor (Altered)",
    "Drake Knight Armor",
    "Drake Knight Armor (Altered)",
    "Blaidd's Armor",
    "Blaidd's Armor (Altered)",
    "Briar Armor",
    "Briar Armor (Altered)",
    "Fingerprint Armor",
    "Fingerprint Armor (Altered)",
    "Royal Remains Armor",
    "All-Knowing Armor",
    "All-Knowing Armor (Altered)",
    "Royal Knight Armor"
]
]

const arms = [
    ["Arms", "Traveler's Manchettes", "Guardian Bracers", "Bloodsoaked Manchettes", "Mushroom Arms"],
    ["", "Astrologer Gloves", "Sorcerer Manchettes", "Battlemage Manchettes", "Errant Sorcerer Manchettes", "Spellblade's Gloves", "Alberich's Bracers", "Preceptor's Gloves", "Azur's Manchettes", "Lusat's Manchettes", "Queen's Bracelets", "Traveling Maiden Gloves", "Gold Bracelets"],
    ["", "Perfumer Gloves", "Traveler's Gloves", "Depraved Perfumer Gloves", "Godskin Apostle Bracelets", "Godskin Noble Bracelets"],
    ["", "Leather Gloves", "Warrior Gauntlets", "Noble's Gloves", "War Surgeon Gloves", "Bandit Manchettes", "Confessor Gloves", "Omenkiller Long Gloves"],
    ["", "Foot Soldier Gauntlets", "Highwayman Gauntlets", "Vulgar Militia Gauntlets", "Nox Bracelets", "Champion Bracers"],
    ["", "Chain Gauntlets", "Iron Gauntlets", "Godrick Soldier Gauntlets", "Raya Lucarian Gauntlets", "Radahn Soldier Gauntlets", "Leyndell Soldier Gauntlets", "Haligtree Gauntlets", "Mausoleum Gauntlets", "Exile Gauntlets", "Kaiden Gauntlets", "Land of Reeds Gauntlets", "White Reed Gauntlets", "Ronin's Gauntlets", "Eccentric's Manchettes", "Blue Silver Bracelets", "Fire Monk Gauntlets", "Blackflame Monk Gauntlets", "Zamor Bracelets", "Black Knife Gauntlets", "Malenia's Gauntlet", "Elden Lord Bracers"],
    ["", "Knight Gauntlets", "Vagabond Knight Gauntlets", "Carian Knight Gauntlets", "Godrick Knight Gauntlets", "Cuckoo Knight Gauntlets", "Redmane Knight Gauntlets", "Gelmir Knight Gauntlets", "Leyndell Knight Gauntlets", "Haligtree Knight Gauntlets", "Mausoleum Knight Gauntlets", "Bloodhound Knight Gauntlets", "Cleanrot Gauntlets"],
    ["", "Raging Wolf Gauntlets", "Hoslow's Gauntlets", "Twinned Gauntlets", "Drake Knight Gauntlets", "Blaidd's Gauntlets", "Briar Gauntlets", "Fingerprint Gauntlets", "Royal Remains Gauntlets", "All-Knowing Gauntlets", "Royal Knight Gauntlets", "Maliketh's Gauntlets"],
    ["", "Banished Knight Gauntlets", "Night's Cavalry Gauntlets", "Veteran's Gauntlets", "Scaled Gauntlets", "Beast Champion Gauntlets", "Tree Sentinel Gauntlets", "Malformed Dragon Gauntlets", "Crucible Gauntlets", "Radahn's Gauntlets"],
    ["", "Lionel's Gauntlets", "Bull-Goat Gauntlets", "Omen Gauntlets", "Fire Prelate Gauntlets"]
  ];

const legs = [
    ["Legs", "Cloth Trousers", "Traveler's Boots", "Commoner's Shoes", "Aristocrat Boots", "Old Aristocrat Shoes", "Page Trousers", "Guardian Greaves", "Prisoner Trousers", "Mushroom Legs"],
    ["", "Astrologer Trousers", "Sorcerer Leggings", "Battlemage Legwraps", "Errant Sorcerer Boots", "Spellblade's Trousers", "Alberich's Trousers", "Preceptor's Trousers", "Old Sorcerer's Legwraps", "Queen's Leggings", "Snow Witch Skirt", "Prophet Trousers", "Traveling Maiden Boots", "Finger Maiden Shoes", "Sage Trousers", "Gold Waistwrap"],
    ["", "Perfumer Sarong", "Traveler's Slops", "Depraved Perfumer Trousers", "Consort's Trousers", "Fur Leggings", "Shaman Leggings", "Godskin Apostle Trousers", "Godskin Noble Trousers", "Sanguine Noble Waistcloth"],
    ["", "Leather Trousers", "Leather Boots", "Warrior Greaves", "Noble's Trousers", "War Surgeon Trousers", "Nomadic Merchant's Trousers", "Bandit Boots", "Confessor Boots", "Omenkiller Boots"],
    ["", "Foot Soldier Greaves", "Vulgar Militia Greaves", "Duelist Greaves", "Rotten Duelist Greaves", "Nox Monk Greaves", "Champion Gaiters"],
    ["", "Chain Leggings", "Godrick Soldier Greaves", "Raya Lucarian Greaves", "Radahn Soldier Greaves", "Leyndell Soldier Greaves", "Haligtree Greaves", "Mausoleum Greaves", "Exile Greaves", "Kaiden Trousers", "Land of Reeds Greaves", "White Reed Greaves", "Ronin's Greaves", "Eccentric's Breeches", "Blue Silver Mail Skirt", "Fire Monk Greaves", "Blackflame Monk Greaves", "Zamor Legwraps", "Black Knife Greaves", "Malenia's Greaves", "Elden Lord Greaves"],
    ["", "Knight Greaves", "Vagabond Knight Greaves", "Carian Knight Greaves", "Godrick Knight Greaves", "Cuckoo Knight Greaves", "Redmane Knight Greaves", "Gelmir Knight Greaves", "Leyndell Knight Greaves", "Haligtree Knight Greaves", "Mausoleum Knight Greaves", "Bloodhound Knight Greaves", "Cleanrot Greaves"],
    ["", "Raging Wolf Greaves", "Hoslow's Greaves", "Twinned Greaves", "Drake Knight Greaves", "Blaidd's Greaves", "Briar Greaves", "Fingerprint Greaves", "Royal Remains Greaves", "All-Knowing Greaves", "Royal Knight Greaves", "Maliketh's Greaves"],
    ["", "Banished Knight Greaves", "Night's Cavalry Greaves", "Veteran's Greaves", "Scaled Greaves", "Beast Champion Greaves", "Tree Sentinel Greaves", "Malformed Dragon Greaves", "Crucible Greaves", "Radahn's Greaves"],
    ["", "Lionel's Greaves", "Bull-Goat Greaves", "Omen Greaves", "Fire Prelate Greaves"]
];

const weapons = [
    ["Weapons"],
    ["Dagger", "Dagger", "Parrying Dagger", "Misericorde", "Great Knife", "Bloodstained Dagger", "Erdsteel Dagger", "Fire Knight's Shortsword", "Elden Ring: Shadow of the Erdtree", "Wakizashi", "Main-gauche", "Celebrant's Sickle", "Ivory Sickle", "Crystal Knife", "Scorpion's Stinger", "Cinquedea", "Glintstone Kris", "Reduvia", "Blade of Calling", "Black Knife", "Smithscript Dagger"],
    ["Straight Swords", "Short Sword", "Longsword", "Broadsword", "Weathered Straight Sword", "Lordsworn's Straight Sword", "Noble's Slender Sword", "Cane Sword", "Stone-Sheathed Sword", "Warhawk's Talon", "Lazuli Glintstone Sword", "Carian Knight's Sword", "Crystal Sword", "Rotten Crystal Sword", "Miquellan Knight's Sword", "Ornamental Straight Sword", "Golden Epitaph", "Sword of St Trina", "Velvet Sword of St Trina", "Regalia of Eochaid", "Coded Sword", "Sword of Night and Flame", "Sword of Light", "Sword of Darkness"],
    ["Light Greatswords", "Milady", "Leda's Sword", "Rellana's Twin Blades"],
    ["Greatswords", "Bastard Sword", "Claymore", "Iron Greatsword", "Lordsworn's Greatsword", "Knight's Greatsword", "Banished Knight's Greatsword", "Forked Greatsword", "Lizard Greatsword", "Flamberge", "Gargoyle's Greatsword", "Gargoyle's Blackblade", "Inseparable Sword", "Sword of Milos", "Marais Executioner's Sword", "Greatsword of Solitude", "Ordovis's Greatsword", "Alabaster Lord's Sword", "Death's Poker", "Helphen's Steeple", "Blasphemous Blade", "Golden Order Greatsword", "Dark Moon Greatsword", "Greatsword of Damnation", "Sacred Relic Sword"],
    ["Colossal Swords", "Zweihander", "Greatsword", "Watchdog's Greatsword", "Fire Knight's Greatsword", "Troll's Golden Sword", "Troll Knight's Sword", "Moonrithyll's Knight Sword", "Royal Greatsword", "Grafted Blade Greatsword", "Ruins Greatsword", "Ancient Meteoric Ore Greatsword", "Starscourge Greatsword", "Greatsword of Radahn (Lord)", "Greatsword of Radahn (Light)", "Godslayer's Greatsword", "Maliketh's Black Blade"],
    ["Thrusting Swords", "Rapier", "Estoc", "Noble's Estoc", "Cleanrot Knight's Sword", "Rogier's Rapier", "Antspur Rapier", "Frozen Needle", "Carian Sorcery Sword"],
    ["Heavy Thrusting Swords", "Great Epee", "Godskin Stitcher", "Queelign's Greatsword", "Bloody Helice", "Dragon King's Cragblade", "Sword Lance"],
    ["Curved Swords", "Scimitar", "Falchion", "Shamshir", "Grossmesser", "Bandit's Curved Sword", "Shotel", "Scavenger's Curved Sword", "Mantis Blade", "Beastman's Curved Sword", "Flowing Curved Sword", "Serpent-God's Curved Sword", "Magma Blade", "Spirit Sword", "Nox Flowing Sword", "Wing of Astel", "Falx", "Dancing Blade of Ranah", "Horned Warrior's Sword", "Eclipse Shotel"],
    ["Curved Greatswords", "Dismounter", "Omen Cleaver", "Monk's Flameblade", "Beastman's Cleaver", "Freyja's Greatsword", "Bloodhound's Fang", "Onyx Lord's Greatsword", "Zamor Curved Sword", "Magma Wyrm's Scalesword", "Horned Warrior's Greatsword", "Morgott's Cursed Sword"],
    ["Backhand Blades", "Backhand Blade", "Smithscript Cirque", "Curseblade's Cirque"],
    ["Katanas", "Uchigatana", "Nagakiba", "Serpentbone Blade", "Meteoric Ore Blade", "Moonveil", "Sword of Night", "Rivers of Blood", "Dragonscale Blade", "Star-Lined Sword", "Hand of Malenia"],
    ["Great Katanas", "Great Katana", "Dragon-Hunter's Great Katana", "Rakshasa's Great Katana"],
    ["Twinblades", "Twinblade", "Twinned Knight Swords", "Black Steel Twinblade", "Godskin Peeler", "Gargoyle's Twinblade", "Gargoyle's Black Blades", "Eleonora's Poleblade", "Euporia"],
    ["Axes", "Hand Axe", "Forked Hatchet", "Forked-Tongue Hatchet", "Battle Axe", "Messmer Soldier's Axe", "Warped Axe", "Jawbone Axe", "Iron Cleaver", "Highland Axe", "Smithscript Axe", "Celebrant's Cleaver", "Sacrificial Axe", "Icerind Hatchet", "Ripple Blade", "Stormhawk Axe", "Rosus' Axe", "Death Knight's Twin Axes"],
    ["Greataxes", "Greataxe", "Crescent Moon Axe", "Longhaft Axe", "Executioner's Greataxe", "Great Omenkiller Cleaver", "Rusted Anchor", "Butchering Knife", "Bonny Butchering Knife", "Gargoyle's Great Axe", "Gargoyle's Black Axe", "Death Knight's Longhaft Axe", "Winged Greathorn", "Axe of Godrick", "Putrescence Cleaver"],
    ["Hammers", "Club", "Curved Club", "Spiked Club", "Stone Club", "Mace", "Morning Star", "Warpick", "Hammer", "Monk's Flamemace", "Varré's Bouquet", "Envoy's Horn", "Nox Flowing Hammer", "Ringed Finger", "Scepter of the All-Knowing", "Flowerstone Gavel", "Marika's Hammer"],
    ["Flails", "Flail", "Nightrider Flail", "Chainlink Flail", "Family Heads", "Serpent Flail", "Bastard's Stars"],
    ["Great Hammers", "Large Club", "Curved Great Club", "Great Mace", "Pickaxe", "Brick Hammer", "Battle Hammer", "Rotten Battle Hammer", "Celebrant's Skull", "Great Stars", "Black Steel Greathammer", "Smithscript Greathammer", "Greathorn Hammer", "Envoy's Long Horn", "Cranial Vessel Candlestand", "Beastclaw Greathammer", "Devourer's Scepter"],
    ["Colossal Weapons", "Duelist Greataxe", "Rotten Greataxe", "Golem's Halberd", "Giant-Crusher", "Prelate's Inferno Crozier", "Great Club", "Troll's Hammer", "Dragon Greatclaw", "Bloodfiend's Arm", "Watchdog's Staff", "Staff of the Avatar", "Rotten Staff", "Envoy's Greathorn", "Ghiza's Wheel", "Fallingstar Beast Jaw", "Anvil Hammer", "Devonia's Hammer", "Axe of Godfrey", "Shadow Sunflower Blossom", "Gazing Finger"],
    ["Spears", "Short Spear", "Iron Spear", "Spear", "Partisan", "Pike", "Swift Spear", "Spiked Spear", "Cross-Naginata", "Clayman's Harpoon", "Bloodfiend's Fork", "Celebrant's Rib-Rake", "Torchpole", "Smithscript Spear", "Inquisitor's Girandole", "Crystal Spear", "Rotten Crystal Spear", "Cleanrot Spear", "Death Ritual Spear", "Bolt of Gransax"],
    ["Great Spears", "Lance", "Messmer Soldier's Spear", "Treespear", "Serpent-Hunter", "Siluria's Tree", "Vyke's War Spear", "Barbed Staff-Spear", "Bloodfiend's Sacred Spear", "Mohgwyn's Sacred Spear", "Spear of the Impaler"],
    ["Reapers", "Scythe", "Grave Scythe", "Halo Scythe", "Winged Scythe", "Obsidian Lamina"]
];

// Export for use in HTML
if (typeof window !== "undefined") {
    window.helms   = helms;
    window.chest   = chest;
    window.arms    = arms;
    window.legs    = legs;
    window.weapons = weapons;
}
