// Stored in JS to make it easier to have static web
// List of lists. First item of internal list is the label for the corresponding lists section
const helms = [
    ["Helmets", "Commoner's Headband", "Commoner's Headband (Altered)", "Aristocrat Headband", "Aristocrat Hat", "Old Aristocrat Cowl",
        "Page Hood",
        "High Page Hood",
        "Guardian Mask",
        "Festive Hood",
        "Festive Hood (Altered)",
        "Blue Festive Hood",
        "Guilty Hood",
        "Prisoner Iron Mask",
        "Blackguard's Iron Mask",
        "Bloodsoaked Mask",
        "Black Dumpling",
        "Mushroom Head",
        "Mushroom Crown"],
    ["", "Astrologer Hood", "Juvenile Scholar Cap", "Karolos Glintstone Crown", "Olivinus Glintstone Crown", 
        "Twinsage Glintstone Crown", "Witch's Glintstone Crown", "Lazuli Glintstone Crown", "Haima Glintstone Crown", 
        "Hierodas Glintstone Crown", "Spellblade's Pointed Hat", "Alberich's Pointed Hat", "Alberich's Pointed Hat (Altered)", 
        "Preceptor's Big Hat", "Mask of Confidence", "Azur's Glintstone Crown", "Lusat's Glintstone Crown", 
        "Queen's Crescent Crown", "Snow Witch Hat", "Fia's Hood", "Prophet Blindfold", "Traveling Maiden Hood", 
        "Finger Maiden Fillet", "Sage Hood", "Greathood", "Radiant Gold Mask"],

    ["", "Perfumer Hood", "Traveler's Hat", "Depraved Perfumer Headscarf", "Ruler's Mask", "Consort's Mask", 
        "Marais Mask", "Great Horned Headband", "Shining Horned Headband", "Godskin Apostle Hood", "Godskin Noble Hood", 
        "Sanguine Noble Hood"],

    ["", "Crimson Tear Scarab", "Cerulean Tear Scarab", "Ash-of-War Scarab", "Glintstone Scarab", "Incantation Scarab", 
        "Imp Head (Cat)", "Imp Head (Wolf)", "Imp Head (Fanged)", "Imp Head (Long-Tongued)", "Imp Head (Corpse)", 
        "Imp Head (Elder)", "Nox Mirrorhelm", "Iji's Mirrorhelm", "Silver Tear Mask", "Envoy Crown", "Octopus Head", 
        "Jar", "Albinauric Mask", "Black Wolf Mask"],

    ["", "Blue Cloth Cowl", "Crimson Hood", "Navy Hood", "White Mask", "Nomadic Merchant's Chapeau", "Bandit Mask", 
        "Black Hood", "Confessor Hood", "Confessor Hood (Altered)", "Omensmirk Mask", "Skeletal Mask"],

    ["", "Foot Soldier Helm", "Foot Soldier Helmet", "Foot Soldier Cap", "Gilded Foot Soldier Cap", "Sacred Crown Helm", 
        "Highwayman Hood", "Vulgar Militia Helm", "Duelist Helm", "Rotten Duelist Helm", "Nox Monk Hood", 
        "Nox Monk Hood (Altered)", "Nox Swordstress Crown", "Nox Swordstress Crown (Altered)", "Night Maiden Twin Crown", 
        "Champion Headband"],

    ["", "Chain Coif", "Iron Helmet", "Godrick Soldier Helm", "Raya Lucarian Helm", "Radahn Soldier Helm", 
        "Leyndell Soldier Helm", "Haligtree Helm", "Exile Hood", "Kaiden Helm", "Land of Reeds Helm", "Okina Mask", 
        "Iron Kasa", "Eccentric's Hood", "Eccentric's Hood (Altered)", "Marionette Soldier Helm", 
        "Marionette Soldier Birdhelm", "Blue Silver Mail Hood", "Fire Monk Hood", "Blackflame Monk Hood", "Zamor Mask", 
        "Black Knife Hood", "Malenia's Winged Helm", "Elden Lord Crown"],

    ["", "Knight Helm", "Vagabond Knight Helm", "Greathelm", "Carian Knight Helm", "Godrick Knight Helm", 
        "Cuckoo Knight Helm", "Redmane Knight Helm", "Gelmir Knight Helm", "Leyndell Knight Helm", "Haligtree Knight Helm", 
        "Bloodhound Knight Helm", "Cleanrot Helm", "Cleanrot Helm (Altered)"],

    ["", "Raging Wolf Helm", "Hoslow's Helm", "Diallos's Mask", "Twinned Helm", "Drake Knight Helm", 
        "Drake Knight Helm (Altered)", "Briar Helm", "Fingerprint Helm", "Royal Remains Helm", "All-Knowing Helm", 
        "Royal Knight Helm", "Maliketh's Helm"],

    ["", "Banished Knight Helm", "Banished Knight Helm (Altered)", "Night's Cavalry Helm", "Night's Cavalry Helm (Altered)", 
        "Veteran's Helm", "Scaled Helm", "Beast Champion Helm", "Tree Sentinel Helm", "Malformed Dragon Helm", 
        "Crucible Axe Helm", "Crucible Tree Helm", "Radahn's Redmane Helm", "Lionel's Helm", "Bull-Goat Helm", 
        "Omen Helm", "Fire Prelate Helm", "Pumpkin Helm"]
]

const chest = [armor_list = [
    "Chest Armor",
    "Cloth Garb",
    "Traveler's Clothes",
    "Commoner's Simple Garb",
    "Commoner's Simple Garb (Altered)",
    "Commoner's Garb",
    "Commoner's Garb (Altered)",
    "Aristocrat Garb",
    "Aristocrat Garb (Altered)",
    "Aristocrat Coat",
    "Old Aristocrat Gown",
    "Page Garb",
    "Page Garb (Altered)",
    "High Page Clothes",
    "High Page Clothes (Altered)",
    "Guardian Garb",
    "Guardian Garb (Full Bloom)",
    "Festive Garb",
    "Festive Garb (Altered)",
    "Blue Festive Garb",
    "Prisoner Clothing",
    "Mushroom Body",
    "Astrologer Robe",
    "Astrologer Robe (Altered)",
    "Juvenile Scholar Robe",
    "Raya Lucarian Robe",
    "Lazuli Robe",
    "Battlemage Robe",
    "Errant Sorcerer Robe",
    "Errant Sorcerer Robe (Altered)",
    "Spellblade's Traveling Attire",
    "Spellblade's Traveling Attire (Altered)",
    "Alberich's Robe",
    "Alberich's Robe (Altered)",
    "Preceptor's Long Gown",
    "Preceptor's Long Gown (Altered)",
    "Azur's Glintstone Robe",
    "Lusat's Robe",
    "Queen's Robe",
    "Snow Witch Robe",
    "Snow Witch Robe (Altered)",
    "Fia's Robe",
    "Fia's Robe (Altered)",
    "Deathbed Dress",
    "Prophet Robe",
    "Prophet Robe (Altered)",
    "Corhyn's Robe",
    "Traveling Maiden Robe",
    "Traveling Maiden Robe (Altered)",
    "Finger Maiden Robe",
    "Finger Maiden Robe (Altered)",
    "Sage Robe",
    "Goldmask's Rags",
    "Perfumer Robe",
    "Perfumer Robe (Altered)",
    "Perfumer's Traveling Garb",
    "Perfumer's Traveling Garb (Altered)",
    "Depraved Perfumer Robe",
    "Depraved Perfumer Robe (Altered)",
    "Upper-Class Robe",
    "Ruler's Robe",
    "Consort's Robe",
    "Official's Attire",
    "Marais Robe",
    "Fur Raiment",
    "Shaman Furs",
    "Godskin Apostle Robe",
    "Godskin Noble Robe",
    "Fell Omen Cloak",
    "Sanguine Noble Robe",
    "Lord of Blood's Robe",
    "Lord of Blood's Robe (Altered)",
    "Leather Armor",
    "Blue Cloth Vest",
    "Noble's Traveling Garb",
    "War Surgeon Gown",
    "War Surgeon Gown (Altered)",
    "Nomadic Merchant's Finery",
    "Nomadic Merchant's Finery (Altered)",
    "Bandit Garb",
    "Confessor Armor",
    "Confessor Armor (Altered)",
    "Omenkiller Robe",
    "Raptor's Black Feathers",
    "Foot Soldier Tabard",
    "Leather-Draped Tabard",
    "Chain-Draped Tabard",
    "Ivory-Draped Tabard",
    "Scarlet Tabard",
    "Bloodsoaked Tabard",
    "Highwayman Cloth Armor",
    "Vulgar Militia Armor",
    "Gravekeeper Cloak",
    "Gravekeeper Cloak (Altered)",
    "Rotten Gravekeeper Cloak",
    "Rotten Gravekeeper Cloak (Altered)",
    "Nox Monk Armor",
    "Nox Monk Armor (Altered)",
    "Nox Swordstress Armor",
    "Nox Swordstress Armor (Altered)",
    "Night Maiden Armor",
    "Champion Pauldron",
    "Chain Armor",
    "Dirty Chainmail",
    "Tree Surcoat",
    "Eye Surcoat",
    "Tree-and-Beast Surcoat",
    "Cuckoo Surcoat",
    "Redmane Surcoat",
    "Erdtree Surcoat",
    "Haligtree Crest Surcoat",
    "Mausoleum Surcoat",
    "Scale Armor",
    "Exile Armor",
    "Kaiden Armor",
    "Land of Reeds Armor",
    "Land of Reeds Armor (Altered)",
    "White Reed Armor",
    "Ronin's Armor",
    "Ronin's Armor (Altered)",
    "Eccentric's Armor",
    "Marionette Soldier Armor",
    "Blue Silver Mail Armor",
    "Blue Silver Mail Armor (Altered)",
    "Fire Monk Armor",
    "Blackflame Monk Armor",
    "Zamor Armor",
    "Black Knife Armor",
    "Black Knife Armor (Altered)",
    "Malenia's Armor",
    "Malenia's Armor (Altered)",
    "Elden Lord Armor",
    "Elden Lord Armor (Altered)",
    "Knight Armor",
    "Vagabond Knight Armor",
    "Vagabond Knight Armor (Altered)",
    "Carian Knight Armor",
    "Carian Knight Armor (Altered)",
    "Godrick Knight Armor",
    "Godrick Knight Armor (Altered)",
    "Cuckoo Knight Armor",
    "Cuckoo Knight Armor (Altered)",
    "Redmane Knight Armor",
    "Redmane Knight Armor (Altered)",
    "Gelmir Knight Armor",
    "Gelmir Knight Armor (Altered)",
    "Leyndell Knight Armor",
    "Leyndell Knight Armor (Altered)",
    "Haligtree Knight Armor",
    "Haligtree Knight Armor (Altered)",
    "Mausoleum Knight Armor",
    "Mausoleum Knight Armor (Altered)",
    "Bloodhound Knight Armor",
    "Bloodhound Knight Armor (Altered)",
    "Cleanrot Armor",
    "Cleanrot Armor (Altered)",
    "Raging Wolf Armor",
    "Raging Wolf Armor (Altered)",
    "Hoslow's Armor",
    "Hoslow's Armor (Altered)",
    "Twinned Armor",
    "Twinned Armor (Altered)",
    "Drake Knight Armor",
    "Drake Knight Armor (Altered)",
    "Blaidd's Armor",
    "Blaidd's Armor (Altered)",
    "Briar Armor",
    "Briar Armor (Altered)",
    "Fingerprint Armor",
    "Fingerprint Armor (Altered)",
    "Royal Remains Armor",
    "All-Knowing Armor",
    "All-Knowing Armor (Altered)",
    "Royal Knight Armor"
]
]


// Export for use in HTML
if (typeof window !== "undefined") {
    window.helms = helms;
    window.chest = chest;
}
